import { GoogleGenAI, Type } from "@google/genai";
import { ProjectProposal } from "../types";

// Initialize Gemini Client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// Define schema without explicit Schema type to avoid import errors
const projectSchema = {
  type: Type.OBJECT,
  properties: {
    title: { type: Type.STRING, description: "A catchy and academic title for the thesis project." },
    difficulty: { type: Type.STRING, enum: ["Beginner", "Intermediate", "Advanced"] },
    category: { type: Type.STRING, description: "e.g., IoT, Automation, Health, Agriculture" },
    problemStatement: { type: Type.STRING, description: "The specific real-world problem being solved." },
    solutionOverview: { type: Type.STRING, description: "High-level explanation of how the Arduino system solves the problem." },
    researchSignificance: { type: Type.STRING, description: "Why this project is worthy of a thesis. Its impact or novelty." },
    hardwareList: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          name: { type: Type.STRING },
          quantity: { type: Type.STRING },
          purpose: { type: Type.STRING }
        },
        required: ["name", "quantity", "purpose"]
      }
    },
    circuitLogic: { type: Type.STRING, description: "Text description of how components are connected (e.g., connect sensor VCC to 5V)." },
    codeSnippet: { type: Type.STRING, description: "The complete or core Arduino C++ code logic." }
  },
  required: ["title", "difficulty", "category", "problemStatement", "solutionOverview", "hardwareList", "circuitLogic", "codeSnippet", "researchSignificance"]
};

export const generateArduinoProjects = async (topic: string): Promise<ProjectProposal[]> => {
  try {
    const prompt = `
      Generate 2 distinct, high-quality Arduino thesis project proposals based on the following user input/problem: "${topic}".
      
      The projects should be suitable for final year engineering or computer science students.
      Focus on feasibility, innovation, and practical application.
      Provide realistic hardware components.
      The code snippet should be substantial enough to demonstrate the core logic.
    `;

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: projectSchema
        },
        temperature: 0.7, // Slightly creative but structured
      },
    });

    const jsonText = response.text;
    if (!jsonText) {
      throw new Error("No content generated by the model.");
    }

    // Clean up markdown formatting if present (e.g., ```json ... ```)
    const cleanJson = jsonText.replace(/^```json\s*/, "").replace(/```$/, "").trim();

    const data = JSON.parse(cleanJson);
    
    // Ensure we always return an array
    if (Array.isArray(data)) {
        return data as ProjectProposal[];
    } else {
        return [data] as ProjectProposal[];
    }

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    
    // Provide more specific error messages
    let message = "Failed to generate project ideas. Please try again.";
    
    if (error.message) {
      if (error.message.includes("401") || error.message.includes("API key")) {
        message = "Invalid or missing API Key. Please check your configuration.";
      } else if (error.message.includes("503")) {
        message = "Service overloaded. Please try again in a few moments.";
      } else {
        message = `API Error: ${error.message}`;
      }
    }
    
    throw new Error(message);
  }
};